# Generated by Django 5.1.2 on 2024-10-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_mayorista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientemayorista',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientemayorista',
            name='telefono',
        ),
    ]
